// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

// actions related to auth
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER'
export const AUTHENTICATION_LOADED = 'AUTHENTICATION_LOADED'
export const UNAUTHENTICATED_USER = 'UNAUTHENTICATED_USER'
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const REMOVE_USER_PROFILE = 'REMOVE_USER_PROFILE'
export const SAVE_ALL_ALGOS = 'SAVE_ALL_ALGOS'
export const SAVE_USER_ALGOS = 'SAVE_USER_ALGOS'
export const SAVE_USER_FOLLOWS = 'SAVE_USER_FOLLOWS'
export const SAVE_USER_SELECTED = 'SAVE_USER_SELECTED'
export const SAVE_TOP_RANKS = 'SAVE_TOP_RANKS'
export const SAVE_NOTIFICATIONS = 'SAVE_NOTIFICATIONS'
