// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

// actions related to auth
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER'
export const AUTHENTICATION_LOADED = 'AUTHENTICATION_LOADED'
export const UNAUTHENTICATED_USER = 'UNAUTHENTICATED_USER'
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const REMOVE_USER_PROFILE = 'REMOVE_USER_PROFILE'
